### PR TITLE
Prompt Images & Add collected prompts to users

### PR DESCRIPTION
**Pull request by rolandobrown**
Went with a simple implementation of a single image, vs many images to get it up. Removed carrierwave gem. Adjusted views. We officially have images.

### CODE REVIEW

**Comment by notnotdrew** [comment]
@rolandobrown It looks like the views directory was moved into the models directory?

**Comment by rolandobrown** [comment]
Fixed.

**Comment by rolandobrown** [comment]
@drewprice @jessicashannon @stefania11 ready to be merged.

**Comment by stefania11** [comment]
:+1:

**Comment by rolandobrown** [comment]
@drewprice @stefania11 @jessicashannon this branch now includes @drewprice's collection branch.

**Pull request merged**
